### ISSUE TITLE
Documentation not found

### ISSUE THREAD

**Issue by YipCyun** [jpadilla/django-rest-framework-jwt#485]
Hi there, the documentation has gone, could anyone find it? THANKS!!

**Comment by jpadilla** [comment]
Recently transferred repository so documentation is now at: http://jpadilla.github.io/django-rest-framework-jwt/

**Comment by YipCyun** [comment]
> Recently transferred repository so documentation is now at: http://jpadilla.github.io/django-rest-framework-jwt/

Thanks!
